lint:
	go vet ./pkg/...
	go vet ./cmd/...

	golint $(go list ./pkg/... | grep -v proto)
	golint ./cmd/...

	go install ./pkg/...
	go install ./cmd/...
gen_proto:
	protoc --go_out=plugins=grpc:. pkg/proto/vv.proto

.PHONY: gen_proto
