check:
	go install ./pkg/...
	go install ./cmd/...

	go test ./pkg/...
	go test ./cmd/...
	
	go vet ./pkg/...
	go vet ./cmd/...

	golint $(go list ./pkg/... | grep -v proto)
	golint ./cmd/...


gen_proto:
	protoc --go_out=plugins=grpc:. pkg/proto/vv.proto

.PHONY: gen_proto check
